spring:
  output:
    ansi:
      enabled: always
  profiles:
    active:
      - env
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}
      password: ${spring.data.redis.password}
      timeout: 3000ms
  mail:
    host: ${spring.mail.host}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
  rabbitmq:
    addresses: ${spring.rabbitmq.addresses}
    username: ${spring.rabbitmq.username}
    password: ${spring.rabbitmq.password}
    virtual-host: ${spring.rabbitmq.virtual-host}

springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha # 接口排序, alpha: 按字母排序

jwt:
  key: abc123456789
  expire: 7
  limit:
    base: 10
    upgrade: 300
    frequency: 30

myweb:
  verify:
    mail-limit: 60
  flow:
    period: 3
    limit: 50
    block: 30
  cors:
    origin: "*"
    credentials: false
    methods: "*"
